nginx:
    extends:
        file: docker-compose.yml
        service: nginx
    build: .
    mem_limit: 128m
    environment:
        - CONSUL=consul
        - CONSUL_AGENT=1
        - ACME_ENV=staging
    links:
        - consul:consul
    ports:
        - 80:80
        - 443:443
        - 9090:9090 # telemetry endpoint

example:
    extends:
        file: docker-compose.yml
        service: example
    build: example-backend/
    environment:
        - CONSUL=consul
        - CONSUL_AGENT=1
    links:
        - consul:consul
    ports:
        - 4000:4000

consul:
    extends:
        file: docker-compose.yml
        service: consul
    ports:
        - 8500:8500
