version: '2.1'

services:
  nginx:
    image: autopilotpattern/nginx-example:${TAG:-latest}
    mem_limit: 128m
    restart: always
    environment:
      - CONSUL_AGENT=1
      - CONSUL=consul
    links:
      - consul:consul
    ports:
      - "8080:80"
    network_mode: bridge


  backend:
    image: autopilotpattern/nginx-backend:${TAG:-latest}
    mem_limit: 128m
    restart: always
    environment:
      - CONSUL=consul
    links:
      - consul:consul
    expose:
      - 3001
    network_mode: bridge


  consul:
    image: autopilotpattern/consul:0.7.2-r0.8
    command: >
      /usr/local/bin/containerpilot
      /bin/consul agent -server
        -bootstrap-expect 1
        -config-dir=/etc/consul
        -ui-dir /ui
    restart: always
    mem_limit: 128m
    expose:
      - 8500
    expose:
      - 53
      - 8300
      - 8301
      - 8302
      - 8400
      - 8500
    network_mode: bridge
